-- MySQL Script generated by MySQL Workbench
-- Thu May 27 01:44:21 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema airbnb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema airbnb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `airbnb` DEFAULT CHARACTER SET utf8 ;
USE `airbnb` ;

-- -----------------------------------------------------
-- Table `airbnb`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`user` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`user` (
                                               `id` BIGINT NOT NULL AUTO_INCREMENT,
                                               `email` VARCHAR(45) NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`accommodation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`accommodation` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`accommodation` (
                                                        `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                        `name` VARCHAR(45) NOT NULL,
    `basic_fee` INT NOT NULL,
    `weekend_fee` INT NULL,
    `cleaning_fee` INT NULL,
    `title_image_url` VARCHAR(1000) NULL,
    `description` VARCHAR(4000) NOT NULL,
    `host_id` BIGINT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_accommodation_user1_idx` (`host_id` ASC),
    CONSTRAINT `fk_accommodation_user1`
    FOREIGN KEY (`host_id`)
    REFERENCES `airbnb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`detail_condition`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`detail_condition` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`detail_condition` (
                                                           `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                           `accommodation_id` BIGINT NOT NULL,
                                                           `room_type` VARCHAR(45) NOT NULL,
    `max_of_people` INT NOT NULL,
    `number_of_toliet` INT NOT NULL,
    `number_of_rooms` INT NULL,
    INDEX `fk_detail_condition_accommodation_idx` (`accommodation_id` ASC),
    PRIMARY KEY (`id`),
    CONSTRAINT `fk_detail_condition_accommodation`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `airbnb`.`accommodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`accomodation_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`accomodation_image` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`accomodation_image` (
                                                             `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                             `accommodation_id` BIGINT NOT NULL,
                                                             `image_url` VARCHAR(1000) NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_accomodation_image_accommodation1_idx` (`accommodation_id` ASC),
    CONSTRAINT `fk_accomodation_image_accommodation1`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `airbnb`.`accommodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`accommodation_option`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`accommodation_option` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`accommodation_option` (
                                                               `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                               `accommodation_id` BIGINT NOT NULL,
                                                               `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_accommodation_options_accommodation1_idx` (`accommodation_id` ASC),
    CONSTRAINT `fk_accommodation_options_accommodation1`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `airbnb`.`accommodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`hash_tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`hash_tag` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`hash_tag` (
                                                   `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                   `accommodation_id` BIGINT NOT NULL,
                                                   `name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_hash_tag_accommodation1_idx` (`accommodation_id` ASC),
    CONSTRAINT `fk_hash_tag_accommodation1`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `airbnb`.`accommodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`reservation` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`reservation` (
                                                      `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                      `start_date` DATE NOT NULL,
                                                      `end_date` DATE NOT NULL,
                                                      `total_fee` INT NOT NULL,
                                                      `accommodation_id` BIGINT NOT NULL,
                                                      `user_id` BIGINT NOT NULL,
                                                      `created_time` DATETIME NOT NULL,
                                                      PRIMARY KEY (`id`),
    INDEX `fk_reservation_accommodation1_idx` (`accommodation_id` ASC),
    INDEX `fk_reservation_user1_idx` (`user_id` ASC),
    CONSTRAINT `fk_reservation_accommodation1`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `airbnb`.`accommodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_reservation_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `airbnb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`special_fee`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`special_fee` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`special_fee` (
                                                      `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                      `start_date` DATE NOT NULL,
                                                      `end_date` DATE NOT NULL,
                                                      `basic_fee` INT NOT NULL,
                                                      `weekend_fee` INT NULL,
                                                      `accommodation_id` BIGINT NOT NULL,
                                                      PRIMARY KEY (`id`),
    INDEX `fk_special_fee_accommodation1_idx` (`accommodation_id` ASC),
    CONSTRAINT `fk_special_fee_accommodation1`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `airbnb`.`accommodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`wish`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`wish` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`wish` (
                                               `id` BIGINT NOT NULL AUTO_INCREMENT,
                                               `accommodation_id` BIGINT NOT NULL,
                                               `user_id` BIGINT NOT NULL,
                                               `created_time` DATETIME NOT NULL,
                                               PRIMARY KEY (`id`),
    INDEX `fk_wish_accommodation1_idx` (`accommodation_id` ASC),
    INDEX `fk_wish_user1_idx` (`user_id` ASC),
    CONSTRAINT `fk_wish_accommodation1`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `airbnb`.`accommodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_wish_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `airbnb`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `airbnb`.`accommodation_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `airbnb`.`accommodation_address` ;

CREATE TABLE IF NOT EXISTS `airbnb`.`accommodation_address` (
                                                                `id` BIGINT NOT NULL AUTO_INCREMENT,
                                                                `accommodation_id` BIGINT NOT NULL,
                                                                `address_name` VARCHAR(200) NOT NULL,
    `road_address_name` VARCHAR(200) NOT NULL,
    `region_1depth_name` VARCHAR(45) NULL,
    `region_2depth_name` VARCHAR(45) NULL,
    `region_3depth_name` VARCHAR(45) NULL,
    `region_4depth_name` VARCHAR(45) NULL,
    `location` POINT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `fk_accommodation_address_accommodation1_idx` (`accommodation_id` ASC),
    SPATIAL INDEX `location_spatial_index` (`location`),
    CONSTRAINT `fk_accommodation_address_accommodation1`
    FOREIGN KEY (`accommodation_id`)
    REFERENCES `airbnb`.`accommodation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
